tui_bug_tracker_proxy:
    path: /{path}
    controller: Tui\BugTrackerBundle\Controller\BugTrackerProxyController::proxy
    requirements:
        path: .+
    methods: [GET, POST, PUT, PATCH, DELETE]
